import { describe, it, expect, vi } from 'vitest';
import type { IVisitorRepository } from '../../../repositories/IVisitorRepository';
import type { IActivityLogRepository } from '../../../repositories/IActivityLogRepository';
import type { Visitor } from '../../../entities/Visitor';
import { checkInVisitor } from '../CheckInVisitor';

// ─── Manual mock factories ────────────────────────────────────────────────────

function makeVisitorRepo(overrides: Partial<IVisitorRepository> = {}): IVisitorRepository {
  return {
    create: vi.fn(async (v: Visitor) => v),
    findById: vi.fn(async () => undefined),
    listActive: vi.fn(async () => []),
    recordCheckOut: vi.fn(async () => {}),
    countActive: vi.fn(async () => 0),
    activePlateExists: vi.fn(async () => false),
    findLastCheckOutByPlate: vi.fn(async () => undefined),
    ...overrides,
  };
}

function makeActivityLogRepo(): IActivityLogRepository {
  return { log: vi.fn(async () => {}) };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const FIXED_ID = 'id-generated-001';
const FIXED_TS = '2026-05-08T12:00:00.000Z';

function makeDeps(overrides: { visitorRepo?: Partial<IVisitorRepository> } = {}) {
  return {
    visitorRepo: makeVisitorRepo(overrides.visitorRepo),
    activityRepo: makeActivityLogRepo(),
    generateId: vi.fn(() => FIXED_ID),
    now: vi.fn(() => FIXED_TS),
  };
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('checkInVisitor', () => {
  it('creates visitor with correct data', async () => {
    // Arrange
    const deps = makeDeps();
    const input = {
      aptCode: 'T01-101',
      plate: 'ABC123',
      vehicleType: 'car' as const,
      name: 'Carlos Ruiz',
      phone: '3001112233',
      minHoursForCourtesy: 6,
      recentHistory: [],
    };
    // Act
    const { visitor } = await checkInVisitor(input, deps);
    // Assert
    expect(visitor.aptCode).toBe('T01-101');
    expect(visitor.plate).toBe('ABC123');
    expect(visitor.vehicleType).toBe('car');
    expect(visitor.name).toBe('Carlos Ruiz');
    expect(visitor.phone).toBe('3001112233');
    expect(visitor.checkOut).toBeNull();
    expect(visitor.hours).toBeNull();
    expect(visitor.baseAmount).toBeNull();
    expect(visitor.tax).toBeNull();
    expect(visitor.total).toBeNull();
  });

  it('applies courtesy when there is no recent history', async () => {
    // Arrange
    const deps = makeDeps();
    const input = {
      aptCode: 'T01-101',
      plate: 'ABC123',
      vehicleType: 'car' as const,
      name: 'Visitor',
      phone: null,
      minHoursForCourtesy: 6,
      recentHistory: [],
    };
    // Act
    const { courtesyApplies, visitor } = await checkInVisitor(input, deps);
    // Assert
    expect(courtesyApplies).toBe(true);
    expect(visitor.courtesyApplies).toBe(true);
  });

  it('does not apply courtesy when there is a recent exit (re-entry)', async () => {
    // Arrange
    const deps = makeDeps();
    const input = {
      aptCode: 'T01-101',
      plate: 'ABC123',
      vehicleType: 'motorcycle' as const,
      name: 'Visitor',
      phone: null,
      minHoursForCourtesy: 6,
      recentHistory: [{ checkedOutAt: new Date().toISOString() }],
    };
    // Act
    const { courtesyApplies, visitor } = await checkInVisitor(input, deps);
    // Assert
    expect(courtesyApplies).toBe(false);
    expect(visitor.courtesyApplies).toBe(false);
  });

  it('calls activityRepo.log with appropriate message', async () => {
    // Arrange
    const deps = makeDeps();
    const input = {
      aptCode: 'T02-203',
      plate: 'XYZ999',
      vehicleType: 'car' as const,
      name: 'Visitor',
      phone: null,
      minHoursForCourtesy: 6,
      recentHistory: [],
    };
    // Act
    await checkInVisitor(input, deps);
    // Assert
    expect(deps.activityRepo.log).toHaveBeenCalledOnce();
    const call = vi.mocked(deps.activityRepo.log).mock.calls[0][0];
    expect(call.msg).toContain('XYZ999');
    expect(call.msg).toContain('T02-203');
  });

  it('calls activityRepo with re-entry message when no courtesy', async () => {
    // Arrange
    const deps = makeDeps();
    const input = {
      aptCode: 'T01-101',
      plate: 'ABC123',
      vehicleType: 'car' as const,
      name: 'Visitor',
      phone: null,
      minHoursForCourtesy: 6,
      recentHistory: [{ checkedOutAt: new Date().toISOString() }],
    };
    // Act
    await checkInVisitor(input, deps);
    // Assert
    const call = vi.mocked(deps.activityRepo.log).mock.calls[0][0];
    expect(call.msg.toLowerCase()).toContain('no courtesy');
  });

  it('uses the id generated by generateId', async () => {
    // Arrange
    const deps = makeDeps();
    const input = {
      aptCode: 'T01-101',
      plate: 'ABC123',
      vehicleType: 'car' as const,
      name: 'Visitor',
      phone: null,
      minHoursForCourtesy: 6,
      recentHistory: [],
    };
    // Act
    const { visitor } = await checkInVisitor(input, deps);
    // Assert
    expect(deps.generateId).toHaveBeenCalled();
    expect(visitor.id).toBe(FIXED_ID);
  });

  it('uses the timestamp from now() for checkIn', async () => {
    // Arrange
    const deps = makeDeps();
    const input = {
      aptCode: 'T01-101',
      plate: 'ABC123',
      vehicleType: 'car' as const,
      name: 'Visitor',
      phone: null,
      minHoursForCourtesy: 6,
      recentHistory: [],
    };
    // Act
    const { visitor } = await checkInVisitor(input, deps);
    // Assert
    expect(deps.now).toHaveBeenCalled();
    expect(visitor.checkIn).toBe(FIXED_TS);
    expect(visitor.createdAt).toBe(FIXED_TS);
    expect(visitor.updatedAt).toBe(FIXED_TS);
  });

  it('calls visitorRepo.create with the constructed visitor', async () => {
    // Arrange
    const deps = makeDeps();
    const input = {
      aptCode: 'T01-101',
      plate: 'ABC123',
      vehicleType: 'car' as const,
      name: 'Visitor',
      phone: null,
      minHoursForCourtesy: 6,
      recentHistory: [],
    };
    // Act
    await checkInVisitor(input, deps);
    // Assert
    expect(deps.visitorRepo.create).toHaveBeenCalledOnce();
    const createArg = vi.mocked(deps.visitorRepo.create).mock.calls[0][0];
    expect(createArg.id).toBe(FIXED_ID);
    expect(createArg.plate).toBe('ABC123');
  });
});
