export * from './IApprovedPlateRepository';
export * from './IBlockedUnitRepository';
export * from './IResidentRepository';
export * from './IVisitorRepository';
export * from './IMonthlyFeeRepository';
export * from './IPricingRepository';
export * from './IActivityLogRepository';
export * from './IDailyCloseRepository';
export * from './IMonthlyPaymentRepository';
